import {
  Measure,
  MeasureGroupTypes,
  Model,
  PopulationType,
} from "@madie/madie-models";

export const multiGroupMeasureFixture: Measure = {
  id: "631f64432c5b7a4c2554b1c3",
  measureHumanReadableId: null,
  measureSetId: null,
  version: null,
  state: null,
  cqlLibraryName: "Sep12Lib",
  ecqmTitle: "Sep12",
  measureName: "Sep12",
  active: true,
  cqlErrors: false,
  cql: 'library Sep12Lib version \'0.0.000\'\n\nusing FHIR version \'4.0.1\'\n\ninclude FHIRHelpers version \'4.0.1\' called FHIRHelpers\n\nparameter "Measurement Period" Interval<DateTime>\n \ncontext Patient\n\ndefine "ipp":\n  ["Encounter"] E where E.period.start during "Measurement Period"\n  \ndefine "boolIpp":\n  true\n  \ndefine "boolDenom":\n  "boolIpp"\n\ndefine "boolNum":\n  false\n\ndefine "denom":\n  "ipp"\n\ndefine "num":\n  ["Encounter"] E where E.status ~ \'finished\'\n  \ndefine function ToCode(coding FHIR.Coding):\n    if coding is null then\n        null\n    else\n        System.Code {\n          code: coding.code.value,\n          system: coding.system.value,\n          version: coding.version.value,\n          display: coding.display.value\n        }\n\ndefine function fun(notPascalCase Integer ):\n  true\n\n\n\n\n',
  elmJson:
    '{"library":{"identifier":{"id":"Sep12Lib","version":"0.0.000"},"schemaIdentifier":{"id":"urn:hl7-org:elm","version":"r1"},"usings":{"def":[{"localIdentifier":"System","uri":"urn:hl7-org:elm-types:r1"},{"localId":"1","locator":"3:1-3:26","localIdentifier":"FHIR","uri":"http://hl7.org/fhir","version":"4.0.1","annotation":[{"type":"Annotation","s":{"r":"1","s":[{"value":["","using "]},{"s":[{"value":["FHIR"]}]},{"value":[" version ","\'4.0.1\'"]}]}}]}]},"includes":{"def":[{"localId":"2","locator":"5:1-5:54","localIdentifier":"FHIRHelpers","path":"FHIRHelpers","version":"4.0.1","annotation":[{"type":"Annotation","s":{"r":"2","s":[{"value":["","include "]},{"s":[{"value":["FHIRHelpers"]}]},{"value":[" version ","\'4.0.1\'"," called ","FHIRHelpers"]}]}}]}]},"parameters":{"def":[{"localId":"5","locator":"7:1-7:49","name":"Measurement Period","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"5","s":[{"value":["","parameter ","\\"Measurement Period\\""," "]},{"r":"4","s":[{"value":["Interval<"]},{"r":"3","s":[{"value":["DateTime"]}]},{"value":[">"]}]}]}}],"resultTyp geSpecifier":{"type":"IntervalTypeSpecifier","pointType":{"name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}},"parameterTypeSpecifier":{"localId":"4","locator":"7:32-7:49","type":"IntervalTypeSpecifier","resultTypeSpecifier":{"type":"IntervalTypeSpecifier","pointType":{"name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}},"pointType":{"localId":"3","locator":"7:41-7:48","resultTypeName":"{urn:hl7-org:elm-types:r1}DateTime","name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}}}]},"contexts":{"def":[{"locator":"9:1-9:15","name":"Patient"}]},"statements":{"def":[{"locator":"9:1-9:15","name":"Patient","context":"Patient","expression":{"type":"SingletonFrom","operand":{"locator":"9:1-9:15","dataType":"{http://hl7.org/fhir}Patient","templateId":"http://hl7.org/fhir/StructureDefinition/Patient","type":"Retrieve"}}},{"localId":"14","locator":"11:1-12:66","name":"ipp","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"14","s":[{"value":["","define ","\\"ipp\\"",":\\n  "]},{"r":"13","s":[{"s":[{"r":"7","s":[{"r":"6","s":[{"r":"6","s":[{"value":["[","\\"Encounter\\"","]"]}]}]},{"value":[" ","E"]}]}]},{"value":[" "]},{"r":"12","s":[{"value":["where "]},{"r":"12","s":[{"r":"10","s":[{"r":"9","s":[{"r":"8","s":[{"value":["E"]}]},{"value":["."]},{"r":"9","s":[{"value":["period"]}]}]},{"value":["."]},{"r":"10","s":[{"value":["start"]}]}]},{"r":"12","value":[" ","during"," "]},{"r":"11","s":[{"value":["\\"Measurement Period\\""]}]}]}]}]}]}}],"resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}},"expression":{"localId":"13","locator":"12:3-12:66","type":"Query","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}},"source":[{"localId":"7","locator":"12:3-12:17","alias":"E","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}},"expression":{"localId":"6","locator":"12:3-12:15","dataType":"{http://hl7.org/fhir}Encounter","templateId":"http://hl7.org/fhir/StructureDefinition/Encounter","type":"Retrieve","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}}}}],"relationship":[],"where":{"localId":"12","locator":"12:19-12:66","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","type":"In","operand":[{"name":"ToDateTime","libraryName":"FHIRHelpers","type":"FunctionRef","operand":[{"localId":"10","locator":"12:25-12:38","resultTypeName":"{http://hl7.org/fhir}dateTime","path":"start","type":"Property","source":{"localId":"9","locator":"12:25-12:32","resultTypeName":"{http://hl7.org/fhir}Period","path":"period","scope":"E","type":"Property"}}]},{"localId":"11","locator":"12:47-12:66","name":"Measurement Period","type":"ParameterRef","resultTypeSpecifier":{"type":"IntervalTypeSpecifier","pointType":{"name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}}}]}}},{"localId":"16","locator":"14:1-15:6","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"boolIpp","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"16","s":[{"r":"15","value":["","define ","\\"boolIpp\\"",":\\n  ","true"]}]}}],"expression":{"localId":"15","locator":"15:3-15:6","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","valueType":"{urn:hl7-org:elm-types:r1}Boolean","value":"true","type":"Literal"}},{"localId":"18","locator":"17:1-18:11","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"boolDenom","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"18","s":[{"value":["","define ","\\"boolDenom\\"",":\\n  "]},{"r":"17","s":[{"value":["\\"boolIpp\\""]}]}]}}],"expression":{"localId":"17","locator":"18:3-18:11","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"boolIpp","type":"ExpressionRef"}},{"localId":"20","locator":"20:1-21:7","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"boolNum","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"20","s":[{"r":"19","value":["","define ","\\"boolNum\\"",":\\n  ","false"]}]}}],"expression":{"localId":"19","locator":"21:3-21:7","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","valueType":"{urn:hl7-org:elm-types:r1}Boolean","value":"false","type":"Literal"}},{"localId":"22","locator":"23:1-24:7","name":"denom","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"22","s":[{"value":["","define ","\\"denom\\"",":\\n  "]},{"r":"21","s":[{"value":["\\"ipp\\""]}]}]}}],"resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}},"expression":{"localId":"21","locator":"24:3-24:7","name":"ipp","type":"ExpressionRef","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}}}},{"localId":"30","locator":"26:1-27:45","name":"num","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"30","s":[{"value":["","define ","\\"num\\"",":\\n  "]},{"r":"29","s":[{"s":[{"r":"24","s":[{"r":"23","s":[{"r":"23","s":[{"value":["[","\\"Encounter\\"","]"]}]}]},{"value":[" ","E"]}]}]},{"value":[" "]},{"r":"28","s":[{"value":["where "]},{"r":"28","s":[{"r":"26","s":[{"r":"25","s":[{"value":["E"]}]},{"value":["."]},{"r":"26","s":[{"value":["status"]}]}]},{"value":[" ","~"," "]},{"r":"27","s":[{"value":["\'finished\'"]}]}]}]}]}]}}],"resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}},"expression":{"localId":"29","locator":"27:3-27:45","type":"Query","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}},"source":[{"localId":"24","locator":"27:3-27:17","alias":"E","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}},"expression":{"localId":"23","locator":"27:3-27:15","dataType":"{http://hl7.org/fhir}Encounter","templateId":"http://hl7.org/fhir/StructureDefinition/Encounter","type":"Retrieve","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{http://hl7.org/fhir}Encounter","type":"NamedTypeSpecifier"}}}}],"relationship":[],"where":{"localId":"28","locator":"27:19-27:45","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","type":"Equivalent","operand":[{"name":"ToString","libraryName":"FHIRHelpers","type":"FunctionRef","operand":[{"localId":"26","locator":"27:25-27:32","resultTypeName":"{http://hl7.org/fhir}EncounterStatus","path":"status","scope":"E","type":"Property"}]},{"localId":"27","locator":"27:36-27:45","resultTypeName":"{urn:hl7-org:elm-types:r1}String","valueType":"{urn:hl7-org:elm-types:r1}String","value":"finished","type":"Literal"}]}}},{"localId":"49","locator":"29:1-38:9","resultTypeName":"{urn:hl7-org:elm-types:r1}Code","name":"ToCode","context":"Patient","accessLevel":"Public","type":"FunctionDef","annotation":[{"type":"Annotation","s":{"r":"49","s":[{"value":["","define function ","ToCode","(","coding"," "]},{"r":"31","s":[{"value":["FHIR",".","Coding"]}]},{"value":["):\\n    "]},{"r":"48","s":[{"r":"48","s":[{"value":["if "]},{"r":"33","s":[{"r":"32","s":[{"value":["coding"]}]},{"value":[" is null"]}]},{"r":"34","value":[" then\\n        ","null","\\n    else\\n        "]},{"r":"47","s":[{"value":["System",".","Code"," {\\n          "]},{"s":[{"value":["code",": "]},{"r":"37","s":[{"r":"36","s":[{"r":"35","s":[{"value":["coding"]}]},{"value":["."]},{"r":"36","s":[{"value":["code"]}]}]},{"value":["."]},{"r":"37","s":[{"value":["value"]}]}]}]},{"value":[",\\n          "]},{"s":[{"value":["system",": "]},{"r":"40","s":[{"r":"39","s":[{"r":"38","s":[{"value":["coding"]}]},{"value":["."]},{"r":"39","s":[{"value":["system"]}]}]},{"value":["."]},{"r":"40","s":[{"value":["value"]}]}]}]},{"value":[",\\n          "]},{"s":[{"value":["version",": "]},{"r":"43","s":[{"r":"42","s":[{"r":"41","s":[{"value":["coding"]}]},{"value":["."]},{"r":"42","s":[{"value":["version"]}]}]},{"value":["."]},{"r":"43","s":[{"value":["value"]}]}]}]},{"value":[",\\n          "]},{"s":[{"value":["display",": "]},{"r":"46","s":[{"r":"45","s":[{"r":"44","s":[{"value":["coding"]}]},{"value":["."]},{"r":"45","s":[{"value":["display"]}]}]},{"value":["."]},{"r":"46","s":[{"value":["value"]}]}]}]},{"value":["\\n        }"]}]}]}]}]}}],"expression":{"localId":"48","locator":"30:5-38:9","resultTypeName":"{urn:hl7-org:elm-types:r1}Code","type":"If","condition":{"localId":"33","locator":"30:8-30:21","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","type":"IsNull","operand":{"localId":"32","locator":"30:8-30:13","resultTypeName":"{http://hl7.org/fhir}Coding","name":"coding","type":"OperandRef"}},"then":{"asType":"{urn:hl7-org:elm-types:r1}Code","type":"As","operand":{"localId":"34","locator":"31:9-31:12","resultTypeName":"{urn:hl7-org:elm-types:r1}Any","type":"Null"}},"else":{"localId":"47","locator":"33:9-38:9","resultTypeName":"{urn:hl7-org:elm-types:r1}Code","classType":"{urn:hl7-org:elm-types:r1}Code","type":"Instance","element":[{"name":"code","value":{"localId":"37","locator":"34:17-34:33","resultTypeName":"{urn:hl7-org:elm-types:r1}String","path":"value","type":"Property","source":{"localId":"36","locator":"34:17-34:27","resultTypeName":"{http://hl7.org/fhir}code","path":"code","type":"Property","source":{"localId":"35","locator":"34:17-34:22","resultTypeName":"{http://hl7.org/fhir}Coding","name":"coding","type":"OperandRef"}}}},{"name":"system","value":{"localId":"40","locator":"35:19-35:37","resultTypeName":"{urn:hl7-org:elm-types:r1}String","path":"value","type":"Property","source":{"localId":"39","locator":"35:19-35:31","resultTypeName":"{http://hl7.org/fhir}uri","path":"system","type":"Property","source":{"localId":"38","locator":"35:19-35:24","resultTypeName":"{http://hl7.org/fhir}Coding","name":"coding","type":"OperandRef"}}}},{"name":"version","value":{"localId":"43","locator":"36:20-36:39","resultTypeName":"{urn:hl7-org:elm-types:r1}String","path":"value","type":"Property","source":{"localId":"42","locator":"36:20-36:33","resultTypeName":"{http://hl7.org/fhir}string","path":"version","type":"Property","source":{"localId":"41","locator":"36:20-36:25","resultTypeName":"{http://hl7.org/fhir}Coding","name":"coding","type":"OperandRef"}}}},{"name":"display","value":{"localId":"46","locator":"37:20-37:39","resultTypeName":"{urn:hl7-org:elm-types:r1}String","path":"value","type":"Property","source":{"localId":"45","locator":"37:20-37:33","resultTypeName":"{http://hl7.org/fhir}string","path":"display","type":"Property","source":{"localId":"44","locator":"37:20-37:25","resultTypeName":"{http://hl7.org/fhir}Coding","name":"coding","type":"OperandRef"}}}}]}},"operand":[{"name":"coding","operandTypeSpecifier":{"localId":"31","locator":"29:31-29:41","resultTypeName":"{http://hl7.org/fhir}Coding","name":"{http://hl7.org/fhir}Coding","type":"NamedTypeSpecifier"}}]},{"localId":"52","locator":"40:1-41:6","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"fun","context":"Patient","accessLevel":"Public","type":"FunctionDef","annotation":[{"type":"Annotation","s":{"r":"52","s":[{"value":["","define function ","fun","(","notPascalCase"," "]},{"r":"50","s":[{"value":["Integer"]}]},{"value":[" ):\\n  "]},{"r":"51","s":[{"r":"51","value":["true"]}]}]}}],"expression":{"localId":"51","locator":"41:3-41:6","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","valueType":"{urn:hl7-org:elm-types:r1}Boolean","value":"true","type":"Literal"},"operand":[{"name":"notPascalCase","operandTypeSpecifier":{"localId":"50","locator":"40:35-40:41","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","name":"{urn:hl7-org:elm-types:r1}Integer","type":"NamedTypeSpecifier"}}]}]}},"externalErrors":[]}',
  groups: [
    {
      id: "6329ce9d1368254f5c078c11",
      scoring: "Ratio",
      populations: [
        {
          id: "20b107a1-ba80-4bab-a95e-7b8834e294fb",
          name: PopulationType.INITIAL_POPULATION,
          definition: "ipp",
          associationType: null,
        },
        {
          id: "977925da-974e-4bd1-9b68-1fa7a53c8380",
          name: PopulationType.DENOMINATOR,
          definition: "denom",
          associationType: null,
        },
        {
          id: "8b6bb54d-5308-4e14-9923-1441e47b87cc",
          name: PopulationType.DENOMINATOR_EXCLUSION,
          definition: "",
          associationType: null,
        },
        {
          id: "515975e7-4043-4dec-8eab-9a4abb0b542a",
          name: PopulationType.NUMERATOR,
          definition: "num",
          associationType: null,
        },
        {
          id: "f8ddb4fd-5b25-4721-b5db-3bf4a3b05f62",
          name: PopulationType.NUMERATOR_EXCLUSION,
          definition: "",
          associationType: null,
        },
      ],
      measureObservations: null,
      groupDescription: "",
      improvementNotation: "",
      rateAggregation: "",
      measureGroupTypes: [MeasureGroupTypes.OUTCOME],
      scoringUnit: "",
      stratifications: [],
      populationBasis: "Encounter",
    },
  ],
  createdAt: "2022-09-12T16:54:27.221Z",
  createdBy: "nate.moraca@semanticbits.com",
  lastModifiedAt: "2022-09-20T14:33:38.584Z",
  lastModifiedBy: "nate.moraca@semanticbits.com",
  measurementPeriodStart: new Date("2022-01-01"),
  measurementPeriodEnd: new Date("2024-12-31"),
  model: Model.QICORE,
  measureMetaData: {
    steward: null,
    description: null,
    copyright: null,
    disclaimer: null,
    rationale: null,
    guidance: null,
  },
  versionId: "0c2904ca-33dc-4583-bcd6-6cd1692f8e0f",
  cmsId: null,
};
