export const qdmCalculationResults = {
  "655e12db1069370e9cde2f80": {
    IPP: 0,
    DENOM: 0,
    DENEX: 0,
    NUMER: 0,
    NUMEX: 0,
    DENEXCEP: 0,
    episode_results: {},
    statement_relevance: {
      MATGlobalCommonFunctionsQDM: {
        HospitalizationWithObservationLengthofStay: "TRUE",
        LengthInDays: "TRUE",
        HospitalizationWithObservation: "TRUE",
        EarliestOf: "NA",
        Earliest: "NA",
        HasStart: "NA",
        NormalizeInterval: "NA",
      },
      TestQDM: {
        Patient: "TRUE",
        "Inpatient Encounters": "TRUE",
        "Initial Population": "TRUE",
        Denominator: "FALSE",
        Numerator: "FALSE",
        "SDE Ethnicity": "NA",
        "SDE Payer": "NA",
        "SDE Race": "NA",
        "SDE Sex": "NA",
        FirstPhysicalExamWithEncounterId: "NA",
        FirstPhysicalExamWithEncounterIdUsingLabTiming: "NA",
        FirstLabTestWithEncounterId: "NA",
        "SDE Results": "NA",
        LengthOfStay: "NA",
      },
    },
    population_relevance: {
      IPP: true,
      DENOM: false,
      DENEX: false,
      NUMER: false,
      NUMEX: false,
      DENEXCEP: false,
    },
    statement_results: {
      MATGlobalCommonFunctionsQDM: {
        HospitalizationWithObservationLengthofStay: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "HospitalizationWithObservationLengthofStay",
          relevance: "TRUE",
          final: "UNHIT",
        },
        LengthInDays: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "LengthInDays",
          relevance: "TRUE",
          final: "UNHIT",
        },
        HospitalizationWithObservation: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "HospitalizationWithObservation",
          relevance: "TRUE",
          final: "UNHIT",
        },
        EarliestOf: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "EarliestOf",
          relevance: "NA",
          final: "NA",
        },
        Earliest: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "Earliest",
          relevance: "NA",
          final: "NA",
        },
        HasStart: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "HasStart",
          relevance: "NA",
          final: "NA",
        },
        NormalizeInterval: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "NormalizeInterval",
          relevance: "NA",
          final: "NA",
        },
      },
      TestQDM: {
        Patient: {
          library_name: "TestQDM",
          statement_name: "Patient",
          relevance: "TRUE",
          final: "FALSE",
        },
        "Inpatient Encounters": {
          raw: [],
          library_name: "TestQDM",
          statement_name: "Inpatient Encounters",
          relevance: "TRUE",
          final: "FALSE",
        },
        "Initial Population": {
          raw: [],
          library_name: "TestQDM",
          statement_name: "Initial Population",
          relevance: "TRUE",
          final: "FALSE",
        },
        Denominator: {
          raw: [],
          library_name: "TestQDM",
          statement_name: "Denominator",
          relevance: "FALSE",
          final: "UNHIT",
        },
        Numerator: {
          raw: [],
          library_name: "TestQDM",
          statement_name: "Numerator",
          relevance: "FALSE",
          final: "UNHIT",
        },
        "SDE Ethnicity": {
          raw: [
            {
              dataElementCodes: [
                {
                  code: "2135-2",
                  system: "2.16.840.1.113883.6.238",
                  version: "1.2",
                  display: "Hispanic or Latino",
                },
              ],
              _id: "656a0995c2da020000043b76",
              qdmTitle: "Patient Characteristic Ethnicity",
              hqmfOid: "2.16.840.1.113883.10.20.28.4.56",
              qdmCategory: "patient_characteristic",
              qdmStatus: "ethnicity",
              qdmVersion: "5.6",
              _type: "QDM::PatientCharacteristicEthnicity",
              id: "656a0995c2da020000043b76",
            },
          ],
          library_name: "TestQDM",
          statement_name: "SDE Ethnicity",
          relevance: "NA",
          final: "NA",
        },
        "SDE Payer": {
          raw: [],
          library_name: "TestQDM",
          statement_name: "SDE Payer",
          relevance: "NA",
          final: "NA",
        },
        "SDE Race": {
          raw: [
            {
              dataElementCodes: [
                {
                  code: "2028-9",
                  system: "2.16.840.1.113883.6.238",
                  version: "1.2",
                  display: "Asian",
                },
              ],
              _id: "656a0992c2da020000043b72",
              qdmTitle: "Patient Characteristic Race",
              hqmfOid: "2.16.840.1.113883.10.20.28.4.59",
              qdmCategory: "patient_characteristic",
              qdmStatus: "race",
              qdmVersion: "5.6",
              _type: "QDM::PatientCharacteristicRace",
              id: "656a0992c2da020000043b72",
            },
          ],
          library_name: "TestQDM",
          statement_name: "SDE Race",
          relevance: "NA",
          final: "NA",
        },
        "SDE Sex": {
          raw: [
            {
              dataElementCodes: [
                {
                  code: "M",
                  system: "2.16.840.1.113883.5.1",
                  version: "2022-11",
                  display: "Male",
                },
              ],
              _id: "656a0993c2da020000043b74",
              qdmTitle: "Patient Characteristic Sex",
              hqmfOid: "2.16.840.1.113883.10.20.28.4.55",
              qdmCategory: "patient_characteristic",
              qdmStatus: "gender",
              qdmVersion: "5.6",
              _type: "QDM::PatientCharacteristicSex",
              id: "656a0993c2da020000043b74",
            },
          ],
          library_name: "TestQDM",
          statement_name: "SDE Sex",
          relevance: "NA",
          final: "NA",
        },
        FirstPhysicalExamWithEncounterId: {
          library_name: "TestQDM",
          statement_name: "FirstPhysicalExamWithEncounterId",
          relevance: "NA",
          final: "NA",
        },
        FirstPhysicalExamWithEncounterIdUsingLabTiming: {
          library_name: "TestQDM",
          statement_name: "FirstPhysicalExamWithEncounterIdUsingLabTiming",
          relevance: "NA",
          final: "NA",
        },
        FirstLabTestWithEncounterId: {
          library_name: "TestQDM",
          statement_name: "FirstLabTestWithEncounterId",
          relevance: "NA",
          final: "NA",
        },
        "SDE Results": {
          raw: {
            FirstHeartRate: [],
            FirstSystolicBloodPressure: [],
            FirstRespiratoryRate: [],
            FirstBodyTemperature: [],
            FirstOxygenSaturation: [],
            FirstBodyWeight: [],
            FirstHematocritLab: [],
            FirstWhiteBloodCellCount: [],
            FirstPotassiumLab: [],
            FirstSodiumLab: [],
            FirstBicarbonateLab: [],
            FirstCreatinineLab: [],
            FirstGlucoseLab: [],
          },
          library_name: "TestQDM",
          statement_name: "SDE Results",
          relevance: "NA",
          final: "NA",
        },
        LengthOfStay: {
          library_name: "TestQDM",
          statement_name: "LengthOfStay",
          relevance: "NA",
          final: "NA",
        },
      },
    },
    clause_results: null,
    patient: "656a098cc2da020000043b67",
    measure: "656cd2e13761fb000092d358",
    state: "complete",
  },
  "656a08a29803a260d239a924": {
    IPP: 0,
    DENOM: 0,
    DENEX: 0,
    NUMER: 0,
    NUMEX: 0,
    DENEXCEP: 0,
    episode_results: {},
    statement_relevance: {
      MATGlobalCommonFunctionsQDM: {
        HospitalizationWithObservationLengthofStay: "TRUE",
        LengthInDays: "TRUE",
        HospitalizationWithObservation: "TRUE",
        EarliestOf: "NA",
        Earliest: "NA",
        HasStart: "NA",
        NormalizeInterval: "NA",
      },
      TestQDM: {
        Patient: "TRUE",
        "Inpatient Encounters": "TRUE",
        "Initial Population": "TRUE",
        Denominator: "TRUE",
        Numerator: "FALSE",
        "SDE Ethnicity": "NA",
        "SDE Payer": "NA",
        "SDE Race": "NA",
        "SDE Sex": "NA",
        FirstPhysicalExamWithEncounterId: "NA",
        FirstPhysicalExamWithEncounterIdUsingLabTiming: "NA",
        FirstLabTestWithEncounterId: "NA",
        "SDE Results": "NA",
        LengthOfStay: "NA",
      },
    },
    population_relevance: {
      IPP: true,
      DENOM: false,
      DENEX: false,
      NUMER: false,
      NUMEX: false,
      DENEXCEP: false,
    },
    statement_results: {
      MATGlobalCommonFunctionsQDM: {
        HospitalizationWithObservationLengthofStay: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "HospitalizationWithObservationLengthofStay",
          relevance: "TRUE",
          final: "UNHIT",
        },
        LengthInDays: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "LengthInDays",
          relevance: "TRUE",
          final: "UNHIT",
        },
        HospitalizationWithObservation: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "HospitalizationWithObservation",
          relevance: "TRUE",
          final: "UNHIT",
        },
        EarliestOf: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "EarliestOf",
          relevance: "NA",
          final: "NA",
        },
        Earliest: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "Earliest",
          relevance: "NA",
          final: "NA",
        },
        HasStart: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "HasStart",
          relevance: "NA",
          final: "NA",
        },
        NormalizeInterval: {
          library_name: "MATGlobalCommonFunctionsQDM",
          statement_name: "NormalizeInterval",
          relevance: "NA",
          final: "NA",
        },
      },
      TestQDM: {
        Patient: {
          library_name: "TestQDM",
          statement_name: "Patient",
          relevance: "TRUE",
          final: "FALSE",
        },
        "Inpatient Encounters": {
          raw: [],
          library_name: "TestQDM",
          statement_name: "Inpatient Encounters",
          relevance: "TRUE",
          final: "FALSE",
        },
        "Initial Population": {
          raw: [],
          library_name: "TestQDM",
          statement_name: "Initial Population",
          relevance: "TRUE",
          final: "FALSE",
        },
        Denominator: {
          raw: [],
          library_name: "TestQDM",
          statement_name: "Denominator",
          relevance: "TRUE",
          final: "FALSE",
        },
        Numerator: {
          raw: [],
          library_name: "TestQDM",
          statement_name: "Numerator",
          relevance: "FALSE",
          final: "UNHIT",
        },
        "SDE Ethnicity": {
          raw: [
            {
              dataElementCodes: [
                {
                  code: "2135-2",
                  system: "2.16.840.1.113883.6.238",
                  version: "1.2",
                  display: "Hispanic or Latino",
                },
              ],
              _id: "656a0995c2da020000043b76",
              qdmTitle: "Patient Characteristic Ethnicity",
              hqmfOid: "2.16.840.1.113883.10.20.28.4.56",
              qdmCategory: "patient_characteristic",
              qdmStatus: "ethnicity",
              qdmVersion: "5.6",
              _type: "QDM::PatientCharacteristicEthnicity",
              id: "656a0995c2da020000043b76",
            },
          ],
          library_name: "TestQDM",
          statement_name: "SDE Ethnicity",
          relevance: "NA",
          final: "NA",
        },
        "SDE Payer": {
          raw: [],
          library_name: "TestQDM",
          statement_name: "SDE Payer",
          relevance: "NA",
          final: "NA",
        },
        "SDE Race": {
          raw: [
            {
              dataElementCodes: [
                {
                  code: "2028-9",
                  system: "2.16.840.1.113883.6.238",
                  version: "1.2",
                  display: "Asian",
                },
              ],
              _id: "656a0992c2da020000043b72",
              qdmTitle: "Patient Characteristic Race",
              hqmfOid: "2.16.840.1.113883.10.20.28.4.59",
              qdmCategory: "patient_characteristic",
              qdmStatus: "race",
              qdmVersion: "5.6",
              _type: "QDM::PatientCharacteristicRace",
              id: "656a0992c2da020000043b72",
            },
          ],
          library_name: "TestQDM",
          statement_name: "SDE Race",
          relevance: "NA",
          final: "NA",
        },
        "SDE Sex": {
          raw: [
            {
              dataElementCodes: [
                {
                  code: "M",
                  system: "2.16.840.1.113883.5.1",
                  version: "2022-11",
                  display: "Male",
                },
              ],
              _id: "656a0993c2da020000043b74",
              qdmTitle: "Patient Characteristic Sex",
              hqmfOid: "2.16.840.1.113883.10.20.28.4.55",
              qdmCategory: "patient_characteristic",
              qdmStatus: "gender",
              qdmVersion: "5.6",
              _type: "QDM::PatientCharacteristicSex",
              id: "656a0993c2da020000043b74",
            },
          ],
          library_name: "TestQDM",
          statement_name: "SDE Sex",
          relevance: "NA",
          final: "NA",
        },
        FirstPhysicalExamWithEncounterId: {
          library_name: "TestQDM",
          statement_name: "FirstPhysicalExamWithEncounterId",
          relevance: "NA",
          final: "NA",
        },
        FirstPhysicalExamWithEncounterIdUsingLabTiming: {
          library_name: "TestQDM",
          statement_name: "FirstPhysicalExamWithEncounterIdUsingLabTiming",
          relevance: "NA",
          final: "NA",
        },
        FirstLabTestWithEncounterId: {
          library_name: "TestQDM",
          statement_name: "FirstLabTestWithEncounterId",
          relevance: "NA",
          final: "NA",
        },
        "SDE Results": {
          raw: {
            FirstHeartRate: [],
            FirstSystolicBloodPressure: [],
            FirstRespiratoryRate: [],
            FirstBodyTemperature: [],
            FirstOxygenSaturation: [],
            FirstBodyWeight: [],
            FirstHematocritLab: [],
            FirstWhiteBloodCellCount: [],
            FirstPotassiumLab: [],
            FirstSodiumLab: [],
            FirstBicarbonateLab: [],
            FirstCreatinineLab: [],
            FirstGlucoseLab: [],
          },
          library_name: "TestQDM",
          statement_name: "SDE Results",
          relevance: "NA",
          final: "NA",
        },
        LengthOfStay: {
          library_name: "TestQDM",
          statement_name: "LengthOfStay",
          relevance: "NA",
          final: "NA",
        },
      },
    },
    clause_results: null,
    patient: "656a098cc2da020000043b67",
    measure: "656cd2e13761fb000092d358",
    state: "complete",
  },
};
