import { DetailedPopulationGroupResult } from "fqm-execution/build/types/Calculator";
import { FinalResult } from "fqm-execution/build/types/Enums";

export const groupResults: DetailedPopulationGroupResult[] = [
  {
    groupId: "633dae796efe1b323e5bf3a8",
    clauseResults: [
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "8",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "9",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "10",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "11",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "12",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "13",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "14",
        raw: [],
        statementName: "Measure Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "15",
        raw: [],
        statementName: "Measure Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "16",
        raw: [],
        statementName: "Measure Population Exclusions",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "17",
        raw: [],
        statementName: "Measure Population Exclusions",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "18",
        raw: [],
        statementName: "Measure Observation",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "19",
        raw: [],
        statementName: "Measure Observation",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "20",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "21",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "22",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "23",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "24",
        raw: ["someo fhir bject"],
        statementName: "Denominator 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "25",
        raw: ["someo fhir bject"],
        statementName: "Denominator 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "26",
        raw: false,
        statementName: "Numerator 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "27",
        raw: false,
        statementName: "Numerator 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "28",
        raw: false,
        statementName: "Numerator 1",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "28",
        raw: false,
        statementName: "some other define",
      },
      {
        final: FinalResult.NA,
        libraryName: "FHIRHelpers",
        localId: "29",
        raw: "",
        statementName: "ToInterval",
      },
      {
        final: FinalResult.NA,
        libraryName: "FHIRHelpers",
        localId: "30",
        raw: "",
        statementName: "ToInterval",
      },
    ],
    episodeResults: [],
    html: "",
    populationRelevance: [],
    statementResults: [],
    stratifierResults: [],
  },
  {
    groupId: "633dae976efe1b323e5bf3a9",
    clauseResults: [
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "8",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "9",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "10",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "11",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "12",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "13",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "14",
        raw: [],
        statementName: "Measure Population",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "15",
        raw: [],
        statementName: "Measure Population",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "16",
        raw: [],
        statementName: "Measure Population Exclusions",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "17",
        raw: [],
        statementName: "Measure Population Exclusions",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "18",
        raw: [],
        statementName: "Measure Observation",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "19",
        raw: [],
        statementName: "Measure Observation",
      },
      {
        final: FinalResult.NA,
        libraryName: "FHIRHelpers",
        localId: "20",
        raw: "",
        statementName: "ToInterval",
      },
      {
        final: FinalResult.NA,
        libraryName: "FHIRHelpers",
        localId: "21",
        raw: "",
        statementName: "ToInterval",
      },
    ],
    episodeResults: [],
    html: "",
    populationRelevance: [],
    statementResults: [],
    stratifierResults: [],
  },
  {
    groupId: "633dae796efe1b323e5bf3a8",
    clauseResults: [
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "8",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "9",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "10",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "11",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "12",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "13",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "14",
        raw: [],
        statementName: "Measure Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "15",
        raw: [],
        statementName: "Measure Population",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "16",
        raw: [],
        statementName: "Measure Population Exclusions",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "17",
        raw: [],
        statementName: "Measure Population Exclusions",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "18",
        raw: [],
        statementName: "Measure Observation",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "19",
        raw: [],
        statementName: "Measure Observation",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "20",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "21",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "22",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "23",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "24",
        raw: ["someo fhir bject"],
        statementName: "Denominator 1",
      },
      {
        final: FinalResult.TRUE,
        libraryName: "OverallCoveragePercentage",
        localId: "25",
        raw: ["someo fhir bject"],
        statementName: "Denominator 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "26",
        raw: false,
        statementName: "Numerator 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "27",
        raw: false,
        statementName: "Numerator 1",
      },
      {
        final: FinalResult.FALSE,
        libraryName: "OverallCoveragePercentage",
        localId: "28",
        raw: false,
        statementName: "Numerator 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "FHIRHelpers",
        localId: "29",
        raw: "",
        statementName: "ToInterval",
      },
      {
        final: FinalResult.NA,
        libraryName: "FHIRHelpers",
        localId: "30",
        raw: "",
        statementName: "ToInterval",
      },
    ],
    episodeResults: [],
    html: "",
    populationRelevance: [],
    statementResults: [],
    stratifierResults: [],
  },
  {
    groupId: "633dae976efe1b323e5bf3a9",
    clauseResults: [
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "8",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "9",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "10",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "11",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "12",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "13",
        raw: [],
        statementName: "Initial Population",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "14",
        raw: [],
        statementName: "Measure Population",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "15",
        raw: [],
        statementName: "Measure Population",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "16",
        raw: [],
        statementName: "Measure Population Exclusions",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "17",
        raw: [],
        statementName: "Measure Population Exclusions",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "18",
        raw: [],
        statementName: "Measure Observation",
      },
      {
        final: FinalResult.UNHIT,
        libraryName: "OverallCoveragePercentage",
        localId: "19",
        raw: [],
        statementName: "Measure Observation",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "20",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "21",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "22",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "23",
        raw: ["someo fhir bject"],
        statementName: "Initial Population 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "24",
        raw: ["someo fhir bject"],
        statementName: "Denominator 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "25",
        raw: ["someo fhir bject"],
        statementName: "Denominator 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "26",
        raw: false,
        statementName: "Numerator 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "27",
        raw: false,
        statementName: "Numerator 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "OverallCoveragePercentage",
        localId: "28",
        raw: false,
        statementName: "Numerator 1",
      },
      {
        final: FinalResult.NA,
        libraryName: "FHIRHelpers",
        localId: "29",
        raw: "",
        statementName: "ToInterval",
      },
      {
        final: FinalResult.NA,
        libraryName: "FHIRHelpers",
        localId: "30",
        raw: "",
        statementName: "ToInterval",
      },
    ],
    episodeResults: [],
    html: "",
    populationRelevance: [],
    statementResults: [],
    stratifierResults: [],
  },
  {
    groupId: "633dae976efe1b323e5bf3d3",
    clauseResults: [],
    episodeResults: [],
    html: "",
    populationRelevance: [],
    statementResults: [],
    stratifierResults: [],
  },
];
