import {
  AggregateFunctionType,
  BaseConfigurationTypes,
  Group,
  Measure,
  MeasureScoring,
  Model,
  PopulationExpectedValue,
  PopulationType,
  TestCase,
} from "@madie/madie-models";
import { CqmExecutionPatientResultsByPopulationSet } from "../QdmCalculationService";
import { ExecutionStatusType } from "../CalculationService";

export interface QdmTestCaseProcessingScenario {
  testCase: TestCase;
  measureGroups: Group[];
  measure: Measure;
  patientResults: CqmExecutionPatientResultsByPopulationSet;
}

export const CV_PATIENT_WITH_OBS_RESULTS: QdmTestCaseProcessingScenario = {
  testCase: {
    id: "6525b28f4a75bf514e67c8d7",
    name: null,
    title: "TC1",
    series: "",
    description: "",
    createdAt: "2023-10-10T20:22:39.373Z",
    createdBy: "nate.moraca@semanticbits.com",
    lastModifiedAt: "2023-10-11T21:06:23.977Z",
    lastModifiedBy: "nate.moraca@semanticbits.com",
    validResource: true,
    json: "{}",
    patientId: "bdd160e5-21f6-45e4-bf60-911778878b4d",
    hapiOperationOutcome: null,
    executionStatus: ExecutionStatusType.NA,
    groupPopulations: [
      {
        groupId: "6525ae434a75bf514e67c8d5",
        scoring: "Continuous Variable",
        populationBasis: "true",
        populationValues: [
          {
            id: "d6c09032-abe1-43f5-812b-6319f50b0f44",
            criteriaReference: null,
            name: PopulationType.INITIAL_POPULATION,
            expected: true,
            actual: false,
          },
          {
            id: "bc57e09b-e2dd-4c46-9170-e8838e999dc6",
            criteriaReference: null,
            name: PopulationType.MEASURE_POPULATION,
            expected: true,
            actual: false,
          },
          {
            id: "1aa2593b-cb91-440a-816a-f5481bee2844",
            criteriaReference: null,
            name: PopulationType.MEASURE_POPULATION_EXCLUSION,
            expected: null,
            actual: null,
          },
          {
            id: "measurePopulationObservation0",
            criteriaReference: "bc57e09b-e2dd-4c46-9170-e8838e999dc6",
            name: PopulationType.MEASURE_POPULATION_OBSERVATION,
            expected: 22,
            actual: null,
          },
        ],
        stratificationValues: [],
      },
    ],
  },
  measureGroups: [
    {
      id: "6525ae434a75bf514e67c8d5",
      scoring: "Continuous Variable",
      populations: [
        {
          id: "d6c09032-abe1-43f5-812b-6319f50b0f44",
          name: PopulationType.INITIAL_POPULATION,
          definition: "Initial Population",
          associationType: null,
          description: "",
        },
        {
          id: "bc57e09b-e2dd-4c46-9170-e8838e999dc6",
          name: PopulationType.MEASURE_POPULATION,
          definition: "Measure Population",
          associationType: null,
          description: "",
        },
        {
          id: "1aa2593b-cb91-440a-816a-f5481bee2844",
          name: PopulationType.MEASURE_POPULATION_EXCLUSION,
          definition: "Measure Population Exception",
          associationType: null,
          description: "",
        },
      ],
      measureObservations: [
        {
          id: "65d84f4a-0edc-4c38-94ed-18f996f8f0c4",
          definition: PopulationType.MEASURE_POPULATION_OBSERVATION,
          description: null,
          criteriaReference: "bc57e09b-e2dd-4c46-9170-e8838e999dc6",
          aggregateMethod: AggregateFunctionType.MAXIMUM,
        },
      ],
      groupDescription: "",
      improvementNotation: "",
      rateAggregation: "",
      measureGroupTypes: null,
      scoringUnit: "",
      stratifications: [],
      populationBasis: "true",
    },
  ],
  measure: {
    id: "6525ae204a75bf514e67c8d3",
    cqlLibraryName: "QdmCvPatient2",
    measureName: "QdmCvPatient2",
    active: true,
    cqlErrors: false,
    errors: [],
    cql: "",
    elmJson: "",
    testCases: [],
    groups: [],
    measurementPeriodStart: new Date("2024-01-01T00:00:00.000+00:00"),
    measurementPeriodEnd: new Date("2024-12-31T23:59:59.999+00:00"),
    model: Model.QDM_5_6,
    scoring: "Continuous Variable",
    baseConfigurationTypes: [BaseConfigurationTypes.OUTCOME],
    patientBasis: true,
  } as unknown as Measure,
  patientResults: {
    "6525ae434a75bf514e67c8d5": {
      IPP: 1,
      MSRPOPL: 1,
      MSRPOPLEX: 0,
      observation_values: [22],
      statement_relevance: {
        QdmCvPatient2: {
          Patient: "NA",
          "SDE Ethnicity": "NA",
          "SDE Payer": "NA",
          "SDE Race": "NA",
          "SDE Sex": "NA",
          "Initial Population": "TRUE",
          "Measure Population": "TRUE",
          "Measure Population Exception": "TRUE",
          "Measure Observation": "TRUE",
          IP2: "NA",
        },
      },
      population_relevance: {
        IPP: true,
        MSRPOPL: true,
        MSRPOPLEX: true,
        observation_values: true,
      },
      statement_results: {
        QdmCvPatient2: {
          Patient: {
            library_name: "QdmCvPatient2",
            statement_name: "Patient",
            relevance: "NA",
            final: "NA",
          },
          "SDE Ethnicity": {
            raw: [],
            library_name: "QdmCvPatient2",
            statement_name: "SDE Ethnicity",
            relevance: "NA",
            final: "NA",
          },
          "SDE Payer": {
            raw: [],
            library_name: "QdmCvPatient2",
            statement_name: "SDE Payer",
            relevance: "NA",
            final: "NA",
          },
          "SDE Race": {
            raw: [],
            library_name: "QdmCvPatient2",
            statement_name: "SDE Race",
            relevance: "NA",
            final: "NA",
          },
          "SDE Sex": {
            raw: [],
            library_name: "QdmCvPatient2",
            statement_name: "SDE Sex",
            relevance: "NA",
            final: "NA",
          },
          "Initial Population": {
            raw: true,
            library_name: "QdmCvPatient2",
            statement_name: "Initial Population",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Population": {
            raw: true,
            library_name: "QdmCvPatient2",
            statement_name: "Measure Population",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Population Exception": {
            raw: false,
            library_name: "QdmCvPatient2",
            statement_name: "Measure Population Exception",
            relevance: "TRUE",
            final: "FALSE",
          },
          "Measure Observation": {
            library_name: "QdmCvPatient2",
            statement_name: "Measure Observation",
            relevance: "TRUE",
            final: "FALSE",
          },
          IP2: {
            raw: true,
            library_name: "QdmCvPatient2",
            statement_name: "IP2",
            relevance: "NA",
            final: "NA",
          },
        },
      },
      clause_results: null,
      patient: "6525b291a430df00002cbec0",
      measure: "652949aa9a1f060000763d86",
      state: "complete",
    },
  },
};

export const CV_EPISODE_WITH_OBS_RESULTS: QdmTestCaseProcessingScenario = {
  testCase: {
    id: "6520233da0940f4a5c9a779e",
    name: null,
    title: "TC1",
    series: "",
    description: "",
    createdAt: "2023-10-06T15:09:49.430Z",
    createdBy: "nate.moraca@semanticbits.com",
    lastModifiedAt: "2023-10-12T21:07:21.573Z",
    lastModifiedBy: "nate.moraca@semanticbits.com",
    validResource: true,
    json: "{}",
    patientId: "dc788bd3-f02b-4b3c-89a2-104c0b6e753e",
    hapiOperationOutcome: null,
    groupPopulations: [
      {
        groupId: "65202333a0940f4a5c9a779d",
        scoring: "Continuous Variable",
        populationBasis: "false",
        populationValues: [
          {
            id: "ad4bbc0d-e955-43de-bef7-29c4ce5c0f07",
            criteriaReference: null,
            name: PopulationType.INITIAL_POPULATION,
            expected: 3,
          },
          {
            id: "e0127aea-baff-4a9f-bff9-d1a980e8b255",
            criteriaReference: null,
            name: PopulationType.MEASURE_POPULATION,
            expected: 3,
          },
          {
            id: "measurePopulationObservation0",
            criteriaReference: "e0127aea-baff-4a9f-bff9-d1a980e8b255",
            name: PopulationType.MEASURE_OBSERVATION,
            expected: 6,
          },
          {
            id: "97942400-e1a1-4857-842b-b1cc0f5ebfd6",
            criteriaReference: null,
            name: PopulationType.MEASURE_POPULATION_EXCLUSION,
            expected: 2,
          },
        ],
        stratificationValues: [],
      },
    ],
    executionStatus: "fail",
  },
  measureGroups: [
    {
      id: "65202333a0940f4a5c9a779d",
      scoring: "Continuous Variable",
      populations: [
        {
          id: "ad4bbc0d-e955-43de-bef7-29c4ce5c0f07",
          name: PopulationType.INITIAL_POPULATION,
          definition: "Initial Population",
          associationType: null,
          description: "",
        },
        {
          id: "e0127aea-baff-4a9f-bff9-d1a980e8b255",
          name: PopulationType.MEASURE_POPULATION,
          definition: "Measure Population",
          associationType: null,
          description: "",
        },
        {
          id: "97942400-e1a1-4857-842b-b1cc0f5ebfd6",
          name: PopulationType.MEASURE_POPULATION_EXCLUSION,
          definition: "Measure Population Exclusion",
          associationType: null,
          description: "",
        },
      ],
      measureObservations: [
        {
          id: "a78c0d1f-7c81-48e3-abf3-4f2595ba5748",
          definition: "Measure Observation",
          description: null,
          criteriaReference: "e0127aea-baff-4a9f-bff9-d1a980e8b255",
          aggregateMethod: AggregateFunctionType.COUNT,
        },
      ],
      groupDescription: "",
      improvementNotation: "",
      rateAggregation: "",
      measureGroupTypes: null,
      scoringUnit: "",
      stratifications: [],
      populationBasis: "false",
    },
  ],
  measure: {
    id: "65202281a0940f4a5c9a779b",
    cqlLibraryName: "QdmCvEpisode2",
    measureName: "QdmCvEpisode2",
    active: true,
    cqlErrors: false,
    errors: [],
    cql: "",
    elmJson: "",
    testCases: [],
    groups: [],
    measurementPeriodStart: new Date("2024-01-01T00:00:00.000+00:00"),
    measurementPeriodEnd: new Date("2024-12-31T23:59:59.999+00:00"),
    model: Model.QDM_5_6,
    scoring: "Continuous Variable",
    baseConfigurationTypes: [BaseConfigurationTypes.OUTCOME],
    patientBasis: false,
  } as unknown as Measure,
  patientResults: {
    "65202333a0940f4a5c9a779d": {
      IPP: 3,
      observation_values: [6],
      MSRPOPL: 3,
      MSRPOPLEX: 2,
      episode_results: {
        "652023464ca40800001ad57d": {
          IPP: 1,
          MSRPOPL: 1,
          MSRPOPLEX: 1,
          observation_values: [],
        },
        "65285ed46bb5ec0000ab8a85": {
          IPP: 1,
          MSRPOPL: 1,
          MSRPOPLEX: 1,
          observation_values: [],
        },
        "65285fc96bb5ec0000ab8e10": {
          IPP: 1,
          MSRPOPL: 1,
          MSRPOPLEX: 0,
          observation_values: [6],
        },
      },
      statement_relevance: {
        QdmCvEpisode2: {
          Patient: "NA",
          "SDE Ethnicity": "NA",
          "SDE Payer": "NA",
          "SDE Race": "NA",
          "SDE Sex": "NA",
          "Initial Population": "TRUE",
          "Measure Population": "TRUE",
          "Measure Population Exclusion": "TRUE",
          "Measure Observation": "TRUE",
          IP2: "NA",
        },
      },
      population_relevance: {
        IPP: true,
        MSRPOPL: true,
        MSRPOPLEX: true,
        observation_values: true,
      },
      statement_results: {
        QdmCvEpisode2: {
          Patient: {
            library_name: "QdmCvEpisode2",
            statement_name: "Patient",
            relevance: "NA",
            final: "NA",
          },
          "SDE Ethnicity": {
            raw: [],
            library_name: "QdmCvEpisode2",
            statement_name: "SDE Ethnicity",
            relevance: "NA",
            final: "NA",
          },
          "SDE Payer": {
            raw: [],
            library_name: "QdmCvEpisode2",
            statement_name: "SDE Payer",
            relevance: "NA",
            final: "NA",
          },
          "SDE Race": {
            raw: [],
            library_name: "QdmCvEpisode2",
            statement_name: "SDE Race",
            relevance: "NA",
            final: "NA",
          },
          "SDE Sex": {
            raw: [],
            library_name: "QdmCvEpisode2",
            statement_name: "SDE Sex",
            relevance: "NA",
            final: "NA",
          },
          "Initial Population": {
            raw: [
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "652023404ca40800001ad578",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "652023464ca40800001ad57d",
                relevantPeriod: {
                  low: "2024-02-08T05:00:00.000+00:00",
                  high: "2024-02-10T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285eb96bb5ec0000ab8a46",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285ed46bb5ec0000ab8a85",
                relevantPeriod: {
                  low: "2024-02-27T05:00:00.000+00:00",
                  high: "2024-03-02T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285fc56bb5ec0000ab8deb",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285fc96bb5ec0000ab8e10",
                relevantPeriod: {
                  low: "2023-12-29T05:00:00.000+00:00",
                  high: "2024-01-04T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
            ],
            library_name: "QdmCvEpisode2",
            statement_name: "Initial Population",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Population": {
            raw: [
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "652023404ca40800001ad578",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "652023464ca40800001ad57d",
                relevantPeriod: {
                  low: "2024-02-08T05:00:00.000+00:00",
                  high: "2024-02-10T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285eb96bb5ec0000ab8a46",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285ed46bb5ec0000ab8a85",
                relevantPeriod: {
                  low: "2024-02-27T05:00:00.000+00:00",
                  high: "2024-03-02T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285fc56bb5ec0000ab8deb",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285fc96bb5ec0000ab8e10",
                relevantPeriod: {
                  low: "2023-12-29T05:00:00.000+00:00",
                  high: "2024-01-04T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
            ],
            library_name: "QdmCvEpisode2",
            statement_name: "Measure Population",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Population Exclusion": {
            raw: [
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "652023404ca40800001ad578",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "652023464ca40800001ad57d",
                relevantPeriod: {
                  low: "2024-02-08T05:00:00.000+00:00",
                  high: "2024-02-10T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285eb96bb5ec0000ab8a46",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285ed46bb5ec0000ab8a85",
                relevantPeriod: {
                  low: "2024-02-27T05:00:00.000+00:00",
                  high: "2024-03-02T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
            ],
            library_name: "QdmCvEpisode2",
            statement_name: "Measure Population Exclusion",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Observation": {
            library_name: "QdmCvEpisode2",
            statement_name: "Measure Observation",
            relevance: "TRUE",
            final: "FALSE",
          },
          IP2: {
            raw: [
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "652023404ca40800001ad578",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "652023464ca40800001ad57d",
                relevantPeriod: {
                  low: "2024-02-08T05:00:00.000+00:00",
                  high: "2024-02-10T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285eb96bb5ec0000ab8a46",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285ed46bb5ec0000ab8a85",
                relevantPeriod: {
                  low: "2024-02-27T05:00:00.000+00:00",
                  high: "2024-03-02T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285fc56bb5ec0000ab8deb",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285fc96bb5ec0000ab8e10",
                relevantPeriod: {
                  low: "2023-12-29T05:00:00.000+00:00",
                  high: "2024-01-04T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
            ],
            library_name: "QdmCvEpisode2",
            statement_name: "IP2",
            relevance: "NA",
            final: "NA",
          },
        },
      },
      clause_results: null,
      patient: "652023404ca40800001ad57a",
      measure: "652d3d01b82d450000f267f7",
      state: "complete",
    },
  },
};

export const RATIO_PATIENTBASED_WITH_OBS_RESULTS: QdmTestCaseProcessingScenario =
  {
    testCase: {
      id: "id1",
      name: "Test Ratio",
      title: "Test1",
      series: "",
      description: "",
      createdAt: "2023-10-30T21:23:06.586Z",
      createdBy: "Test1",
      lastModifiedAt: "2023-10-12T21:07:21.573Z",
      lastModifiedBy: "Test1",
      validResource: true,
      json: '{"qdmVersion":"5.6","dataElements":[{"dataElementCodes":[{"code":"448951000124107","system":"2.16.840.1.113883.6.96","version":null,"display":"Admission to observation unit (procedure)"}],"_id":"65401ebfd9e14800002ab193","participant":[],"relatedTo":[],"qdmTitle":"Encounter, Performed","hqmfOid":"2.16.840.1.113883.10.20.28.4.5","qdmCategory":"encounter","qdmStatus":"performed","qdmVersion":"5.6","_type":"QDM::EncounterPerformed","description":"Encounter, Performed: Observation Services","codeListId":"2.16.840.1.113762.1.4.1111.143","id":"65401ec2d9e14800002ab19c","authorDatetime":"2023-10-26T00:00:00.000+00:00","relevantPeriod":{"low":"2023-10-18T00:00:00.000+00:00","high":"2023-10-25T00:00:00.000+00:00","lowClosed":true,"highClosed":true},"facilityLocations":[],"diagnoses":[]},{"dataElementCodes":[{"code":"4525004","system":"2.16.840.1.113883.6.96","version":null,"display":"Emergency department patient visit (procedure)"}],"_id":"65401ebfd9e14800002ab197","participant":[],"relatedTo":[],"qdmTitle":"Encounter, Performed","hqmfOid":"2.16.840.1.113883.10.20.28.4.5","qdmCategory":"encounter","qdmStatus":"performed","qdmVersion":"5.6","_type":"QDM::EncounterPerformed","description":"Encounter, Performed: Emergency Department Visit","codeListId":"2.16.840.1.113883.3.117.1.7.1.292","id":"65401ed9d9e14800002ab1b2","relevantPeriod":{"low":"2023-10-19T00:00:00.000+00:00","high":"2023-10-24T00:00:00.000+00:00","lowClosed":true,"highClosed":true},"facilityLocations":[],"diagnoses":[]}],"_id":"65401ebfd9e14800002ab199"}',
      patientId: "dc788bd3-f02b-4b3c-89a2-104c0b6e753e",
      hapiOperationOutcome: null,
      groupPopulations: [
        {
          groupId: "Group1",
          scoring: MeasureScoring.RATIO,
          populationBasis: "true",
          populationValues: [
            {
              name: "initialPopulation",
              expected: true,
              actual: false,
            },
            {
              name: "initialPopulation",
              expected: true,
              actual: false,
            },
            {
              name: "denominator",
              expected: true,
              actual: false,
            },
            {
              name: "numerator",
              expected: true,
              actual: false,
            },
            {
              name: "numeratorObservation",
              expected: "30",
              actual: null,
            },
          ] as PopulationExpectedValue[],
          stratificationValues: [],
        },
      ],
      executionStatus: "fail",
    },
    measureGroups: [
      {
        id: "Group1",
        scoring: MeasureScoring.RATIO,
        populations: [
          {
            id: "g1pop1",
            name: PopulationType.INITIAL_POPULATION,
            definition: "Initial Population",
            associationType: null,
            description: "",
          },
          {
            id: "g1pop2",
            name: PopulationType.DENOMINATOR,
            definition: "foo3",
            associationType: null,
            description: "",
          },
          {
            id: "g1pop3",
            name: PopulationType.DENOMINATOR_EXCLUSION,
            definition: "foo7",
            associationType: null,
            description: "",
          },
          {
            id: "g1pop4",
            name: PopulationType.NUMERATOR,
            definition: "foo2",
            associationType: null,
            description: "",
          },
          {
            id: "g1pop5",
            name: PopulationType.NUMERATOR_EXCLUSION,
            definition: "foo12",
            associationType: null,
            description: "",
          },
        ],
        measureObservations: [
          {
            id: "observ1",
            definition: "Numer Observation",
            description: null,
            criteriaReference: "g1pop4",
            aggregateMethod: "Count",
          },
        ],
        measureGroupTypes: null,
      },
    ],
    measure: {
      id: "653a7e0ea58fe605001e6c5e",
      cqlLibraryName: "QdmRatioParientBased",
      measureName: "QdmRatioParientBased",
      active: true,
      cqlErrors: false,
      errors: [],
      cql: 'library QdmRatioParientBased version \'0.0.000\'\n\nusing QDM version \'5.6\'\n\ncodesystem "LOINC": \'urn:oid:2.16.840.1.113883.6.1\' \ncodesystem "SNOMEDCT": \'urn:oid:2.16.840.1.113883.6.96\' \n\n\nvalueset "Chemistry Tests": \'urn:oid:2.16.840.1.113762.1.4.1147.82\'\nvalueset "Emergency Department Visit": \'urn:oid:2.16.840.1.113883.3.117.1.7.1.292\'\nvalueset "Encounter Inpatient": \'urn:oid:2.16.840.1.113883.3.666.5.307\'\nvalueset "Ethnicity": \'urn:oid:2.16.840.1.114222.4.11.837\' \nvalueset "Lab Communications": \'urn:oid:2.16.840.1.113762.1.4.1147.61\' \nvalueset "Observation Services": \'urn:oid:2.16.840.1.113762.1.4.1111.143\' \n\ncode "Birth date": \'21112-8\' from "LOINC" display \'Birth date\'\ncode "Detected (qualifier value)": \'260373001\' from "SNOMEDCT" display \'Detected (qualifier value)\'\n\nparameter "Measurement Period" Interval<DateTime>\n\ncontext Patient\n\ndefine "Initial Population":\n  exists "Qualifying Encounters"\n   // with "Communication" ValueCommunicated\n//      such that ValueCommunicated.sentDatetime during QEncounters.relevantPeriod\n\ndefine "Denominator":\n  "Initial Population"\n  \ndefine "Numerator":\n exists ["Encounter, Performed": "Emergency Department Visit"] Encounter\n        where Encounter.relevantPeriod ends during "Measurement Period"\n  \n\ndefine "Qualifying Encounters":\n  ( ["Encounter, Performed": "Encounter Inpatient"]\n    union ["Encounter, Performed": "Emergency Department Visit"]\n    union ["Encounter, Performed": "Observation Services"] ) Encounter\n    where Encounter.relevantPeriod ends during "Measurement Period"\n\n\ndefine "Denonimator Exclusion":\n    exists ["Encounter, Performed": "Observation Services"]\n   \ndefine function "Denom Observation"():\n 10  \n\ndefine function "Numer Observation"():\n 12  \n',
      elmJson:
        '{"library":{"identifier":{"id":"QdmRatioParientBased","version":"0.0.000"},"schemaIdentifier":{"id":"urn:hl7-org:elm","version":"r1"},"usings":{"def":[{"localIdentifier":"System","uri":"urn:hl7-org:elm-types:r1"},{"localId":"1","locator":"3:1-3:23","localIdentifier":"QDM","uri":"urn:healthit-gov:qdm:v5_6","version":"5.6","annotation":[{"type":"Annotation","s":{"r":"1","s":[{"value":["","using "]},{"s":[{"value":["QDM"]}]},{"value":[" version ","\'5.6\'"]}]}}]}]},"parameters":{"def":[{"localId":"16","locator":"19:1-19:49","name":"Measurement Period","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"16","s":[{"value":["","parameter ","\\"Measurement Period\\""," "]},{"r":"15","s":[{"value":["Interval<"]},{"r":"14","s":[{"value":["DateTime"]}]},{"value":[">"]}]}]}}],"resultTypeSpecifier":{"type":"IntervalTypeSpecifier","pointType":{"name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}},"parameterTypeSpecifier":{"localId":"15","locator":"19:32-19:49","type":"IntervalTypeSpecifier","resultTypeSpecifier":{"type":"IntervalTypeSpecifier","pointType":{"name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}},"pointType":{"localId":"14","locator":"19:41-19:48","resultTypeName":"{urn:hl7-org:elm-types:r1}DateTime","name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}}}]},"codeSystems":{"def":[{"localId":"2","locator":"5:1-5:51","resultTypeName":"{urn:hl7-org:elm-types:r1}CodeSystem","name":"LOINC","id":"urn:oid:2.16.840.1.113883.6.1","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"2","s":[{"value":["","codesystem ","\\"LOINC\\"",": ","\'urn:oid:2.16.840.1.113883.6.1\'"]}]}}]},{"localId":"3","locator":"6:1-6:55","resultTypeName":"{urn:hl7-org:elm-types:r1}CodeSystem","name":"SNOMEDCT","id":"urn:oid:2.16.840.1.113883.6.96","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"3","s":[{"value":["","codesystem ","\\"SNOMEDCT\\"",": ","\'urn:oid:2.16.840.1.113883.6.96\'"]}]}}]}]},"valueSets":{"def":[{"localId":"4","locator":"9:1-9:67","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Chemistry Tests","id":"urn:oid:2.16.840.1.113762.1.4.1147.82","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"4","s":[{"value":["","valueset ","\\"Chemistry Tests\\"",": ","\'urn:oid:2.16.840.1.113762.1.4.1147.82\'"]}]}}]},{"localId":"5","locator":"10:1-10:82","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Emergency Department Visit","id":"urn:oid:2.16.840.1.113883.3.117.1.7.1.292","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"5","s":[{"value":["","valueset ","\\"Emergency Department Visit\\"",": ","\'urn:oid:2.16.840.1.113883.3.117.1.7.1.292\'"]}]}}]},{"localId":"6","locator":"11:1-11:71","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Encounter Inpatient","id":"urn:oid:2.16.840.1.113883.3.666.5.307","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"6","s":[{"value":["","valueset ","\\"Encounter Inpatient\\"",": ","\'urn:oid:2.16.840.1.113883.3.666.5.307\'"]}]}}]},{"localId":"7","locator":"12:1-12:58","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Ethnicity","id":"urn:oid:2.16.840.1.114222.4.11.837","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"7","s":[{"value":["","valueset ","\\"Ethnicity\\"",": ","\'urn:oid:2.16.840.1.114222.4.11.837\'"]}]}}]},{"localId":"8","locator":"13:1-13:70","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Lab Communications","id":"urn:oid:2.16.840.1.113762.1.4.1147.61","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"8","s":[{"value":["","valueset ","\\"Lab Communications\\"",": ","\'urn:oid:2.16.840.1.113762.1.4.1147.61\'"]}]}}]},{"localId":"9","locator":"14:1-14:73","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Observation Services","id":"urn:oid:2.16.840.1.113762.1.4.1111.143","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"9","s":[{"value":["","valueset ","\\"Observation Services\\"",": ","\'urn:oid:2.16.840.1.113762.1.4.1111.143\'"]}]}}]}]},"codes":{"def":[{"localId":"11","locator":"16:1-16:62","resultTypeName":"{urn:hl7-org:elm-types:r1}Code","name":"Birth date","id":"21112-8","display":"Birth date","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"11","s":[{"value":["","code ","\\"Birth date\\"",": ","\'21112-8\'"," from "]},{"r":"10","s":[{"value":["\\"LOINC\\""]}]},{"value":[" display ","\'Birth date\'"]}]}}],"codeSystem":{"localId":"10","locator":"16:35-16:41","resultTypeName":"{urn:hl7-org:elm-types:r1}CodeSystem","name":"LOINC"}},{"localId":"13","locator":"17:1-17:99","resultTypeName":"{urn:hl7-org:elm-types:r1}Code","name":"Detected (qualifier value)","id":"260373001","display":"Detected (qualifier value)","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"13","s":[{"value":["","code ","\\"Detected (qualifier value)\\"",": ","\'260373001\'"," from "]},{"r":"12","s":[{"value":["\\"SNOMEDCT\\""]}]},{"value":[" display ","\'Detected (qualifier value)\'"]}]}}],"codeSystem":{"localId":"12","locator":"17:53-17:62","resultTypeName":"{urn:hl7-org:elm-types:r1}CodeSystem","name":"SNOMEDCT"}}]},"contexts":{"def":[{"locator":"21:1-21:15","name":"Patient"}]},"statements":{"def":[{"locator":"21:1-21:15","name":"Patient","context":"Patient","expression":{"type":"SingletonFrom","operand":{"locator":"21:1-21:15","dataType":"{urn:healthit-gov:qdm:v5_6}Patient","templateId":"Patient","type":"Retrieve"}}},{"localId":"28","locator":"36:1-40:67","name":"Qualifying Encounters","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"28","s":[{"value":["","define ","\\"Qualifying Encounters\\"",":\\n  "]},{"r":"27","s":[{"s":[{"r":"22","s":[{"r":"21","s":[{"value":["( "]},{"r":"21","s":[{"r":"19","s":[{"r":"17","s":[{"value":["[","\\"Encounter, Performed\\"",": "]},{"s":[{"value":["\\"Encounter Inpatient\\""]}]},{"value":["]"]}]},{"value":["\\n    union "]},{"r":"18","s":[{"value":["[","\\"Encounter, Performed\\"",": "]},{"s":[{"value":["\\"Emergency Department Visit\\""]}]},{"value":["]"]}]}]},{"value":["\\n    union "]},{"r":"20","s":[{"value":["[","\\"Encounter, Performed\\"",": "]},{"s":[{"value":["\\"Observation Services\\""]}]},{"value":["]"]}]}]},{"value":[" )"]}]},{"value":[" ","Encounter"]}]}]},{"value":["\\n    "]},{"r":"26","s":[{"value":["where "]},{"r":"26","s":[{"r":"24","s":[{"r":"23","s":[{"value":["Encounter"]}]},{"value":["."]},{"r":"24","s":[{"value":["relevantPeriod"]}]}]},{"r":"26","value":[" ","ends during"," "]},{"r":"25","s":[{"value":["\\"Measurement Period\\""]}]}]}]}]}]}}],"resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"expression":{"localId":"27","locator":"37:3-40:67","type":"Query","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"source":[{"localId":"22","locator":"37:3-39:70","alias":"Encounter","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"expression":{"localId":"21","locator":"37:3-39:60","type":"Union","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"operand":[{"localId":"19","locator":"37:5-38:64","type":"Union","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"operand":[{"localId":"17","locator":"37:5-37:51","dataType":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","templateId":"PositiveEncounterPerformed","codeProperty":"code","codeComparator":"in","type":"Retrieve","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"codes":{"locator":"37:30-37:50","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Encounter Inpatient","preserve":true,"type":"ValueSetRef"}},{"localId":"18","locator":"38:11-38:64","dataType":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","templateId":"PositiveEncounterPerformed","codeProperty":"code","codeComparator":"in","type":"Retrieve","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"codes":{"locator":"38:36-38:63","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Emergency Department Visit","preserve":true,"type":"ValueSetRef"}}]},{"localId":"20","locator":"39:11-39:58","dataType":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","templateId":"PositiveEncounterPerformed","codeProperty":"code","codeComparator":"in","type":"Retrieve","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"codes":{"locator":"39:36-39:57","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Observation Services","preserve":true,"type":"ValueSetRef"}}]}}],"relationship":[],"where":{"localId":"26","locator":"40:5-40:67","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","type":"In","operand":[{"locator":"40:36-40:39","type":"End","operand":{"localId":"24","locator":"40:11-40:34","path":"relevantPeriod","scope":"Encounter","type":"Property","resultTypeSpecifier":{"type":"IntervalTypeSpecifier","pointType":{"name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}}}},{"localId":"25","locator":"40:48-40:67","name":"Measurement Period","type":"ParameterRef","resultTypeSpecifier":{"type":"IntervalTypeSpecifier","pointType":{"name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}}}]}}},{"localId":"31","locator":"23:1-24:32","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"Initial Population","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"31","s":[{"value":["","define ","\\"Initial Population\\"",":\\n  "]},{"r":"30","s":[{"value":["exists "]},{"r":"29","s":[{"value":["\\"Qualifying Encounters\\""]}]}]}]}}],"expression":{"localId":"30","locator":"24:3-24:32","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","type":"Exists","operand":{"localId":"29","locator":"24:10-24:32","name":"Qualifying Encounters","type":"ExpressionRef","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}}}}},{"localId":"33","locator":"28:1-29:22","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"Denominator","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"33","s":[{"value":["// with \\"Communication\\" ValueCommunicated\\n//      such that ValueCommunicated.sentDatetime during QEncounters.relevantPeriod\\n\\n","define ","\\"Denominator\\"",":\\n  "]},{"r":"32","s":[{"value":["\\"Initial Population\\""]}]}]}}],"expression":{"localId":"32","locator":"29:3-29:22","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"Initial Population","type":"ExpressionRef"}},{"localId":"42","locator":"31:1-33:71","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"Numerator","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"42","s":[{"value":["","define ","\\"Numerator\\"",":\\n "]},{"r":"41","s":[{"value":["exists "]},{"r":"40","s":[{"s":[{"r":"35","s":[{"r":"34","s":[{"r":"34","s":[{"value":["[","\\"Encounter, Performed\\"",": "]},{"s":[{"value":["\\"Emergency Department Visit\\""]}]},{"value":["]"]}]}]},{"value":[" ","Encounter"]}]}]},{"value":["\\n        "]},{"r":"39","s":[{"value":["where "]},{"r":"39","s":[{"r":"37","s":[{"r":"36","s":[{"value":["Encounter"]}]},{"value":["."]},{"r":"37","s":[{"value":["relevantPeriod"]}]}]},{"r":"39","value":[" ","ends during"," "]},{"r":"38","s":[{"value":["\\"Measurement Period\\""]}]}]}]}]}]}]}}],"expression":{"localId":"41","locator":"32:2-33:71","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","type":"Exists","operand":{"localId":"40","locator":"32:9-33:71","type":"Query","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"source":[{"localId":"35","locator":"32:9-32:72","alias":"Encounter","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"expression":{"localId":"34","locator":"32:9-32:62","dataType":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","templateId":"PositiveEncounterPerformed","codeProperty":"code","codeComparator":"in","type":"Retrieve","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"codes":{"locator":"32:34-32:61","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Emergency Department Visit","preserve":true,"type":"ValueSetRef"}}}],"relationship":[],"where":{"localId":"39","locator":"33:9-33:71","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","type":"In","operand":[{"locator":"33:40-33:43","type":"End","operand":{"localId":"37","locator":"33:15-33:38","path":"relevantPeriod","scope":"Encounter","type":"Property","resultTypeSpecifier":{"type":"IntervalTypeSpecifier","pointType":{"name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}}}},{"localId":"38","locator":"33:52-33:71","name":"Measurement Period","type":"ParameterRef","resultTypeSpecifier":{"type":"IntervalTypeSpecifier","pointType":{"name":"{urn:hl7-org:elm-types:r1}DateTime","type":"NamedTypeSpecifier"}}}]}}}},{"localId":"45","locator":"43:1-44:59","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"Denonimator Exclusion","context":"Patient","accessLevel":"Public","annotation":[{"type":"Annotation","s":{"r":"45","s":[{"value":["","define ","\\"Denonimator Exclusion\\"",":\\n    "]},{"r":"44","s":[{"value":["exists "]},{"r":"43","s":[{"value":["[","\\"Encounter, Performed\\"",": "]},{"s":[{"value":["\\"Observation Services\\""]}]},{"value":["]"]}]}]}]}}],"expression":{"localId":"44","locator":"44:5-44:59","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","type":"Exists","operand":{"localId":"43","locator":"44:12-44:59","dataType":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","templateId":"PositiveEncounterPerformed","codeProperty":"code","codeComparator":"in","type":"Retrieve","resultTypeSpecifier":{"type":"ListTypeSpecifier","elementType":{"name":"{urn:healthit-gov:qdm:v5_6}PositiveEncounterPerformed","type":"NamedTypeSpecifier"}},"codes":{"locator":"44:37-44:58","resultTypeName":"{urn:hl7-org:elm-types:r1}ValueSet","name":"Observation Services","preserve":true,"type":"ValueSetRef"}}}},{"localId":"47","locator":"46:1-47:3","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","name":"Denom Observation","context":"Patient","accessLevel":"Public","type":"FunctionDef","annotation":[{"type":"Annotation","s":{"r":"47","s":[{"value":["","define function ","\\"Denom Observation\\"","():\\n "]},{"r":"46","s":[{"r":"46","value":["10"]}]}]}}],"expression":{"localId":"46","locator":"47:2-47:3","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","valueType":"{urn:hl7-org:elm-types:r1}Integer","value":"10","type":"Literal"},"operand":[]},{"localId":"49","locator":"49:1-50:3","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","name":"Numer Observation","context":"Patient","accessLevel":"Public","type":"FunctionDef","annotation":[{"type":"Annotation","s":{"r":"49","s":[{"value":["","define function ","\\"Numer Observation\\"","():\\n "]},{"r":"48","s":[{"r":"48","value":["12"]}]}]}}],"expression":{"localId":"48","locator":"50:2-50:3","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","valueType":"{urn:hl7-org:elm-types:r1}Integer","value":"12","type":"Literal"},"operand":[]}]}},"externalErrors":[]}',
      elmXml: null,
      testCases: [
        {
          id: "65401eba1b2c1c16e90c39fb",
          name: null,
          title: "Test1",
          series: "",
          description: "",
          createdAt: "2023-10-30T21:23:06.586Z",
          createdBy: "Test1",
          lastModifiedAt: "2023-10-30T21:27:36.851Z",
          lastModifiedBy: "Test1",
          validResource: true,
          json: '{"qdmVersion":"5.6","dataElements":[{"dataElementCodes":[{"code":"448951000124107","system":"2.16.840.1.113883.6.96","version":null,"display":"Admission to observation unit (procedure)"}],"_id":"65401ebfd9e14800002ab193","participant":[],"relatedTo":[],"qdmTitle":"Encounter, Performed","hqmfOid":"2.16.840.1.113883.10.20.28.4.5","qdmCategory":"encounter","qdmStatus":"performed","qdmVersion":"5.6","_type":"QDM::EncounterPerformed","description":"Encounter, Performed: Observation Services","codeListId":"2.16.840.1.113762.1.4.1111.143","id":"65401ec2d9e14800002ab19c","authorDatetime":"2023-10-26T00:00:00.000+00:00","relevantPeriod":{"low":"2023-10-18T00:00:00.000+00:00","high":"2023-10-25T00:00:00.000+00:00","lowClosed":true,"highClosed":true},"facilityLocations":[],"diagnoses":[]},{"dataElementCodes":[{"code":"4525004","system":"2.16.840.1.113883.6.96","version":null,"display":"Emergency department patient visit (procedure)"}],"_id":"65401ebfd9e14800002ab197","participant":[],"relatedTo":[],"qdmTitle":"Encounter, Performed","hqmfOid":"2.16.840.1.113883.10.20.28.4.5","qdmCategory":"encounter","qdmStatus":"performed","qdmVersion":"5.6","_type":"QDM::EncounterPerformed","description":"Encounter, Performed: Emergency Department Visit","codeListId":"2.16.840.1.113883.3.117.1.7.1.292","id":"65401ed9d9e14800002ab1b2","relevantPeriod":{"low":"2023-10-19T00:00:00.000+00:00","high":"2023-10-24T00:00:00.000+00:00","lowClosed":true,"highClosed":true},"facilityLocations":[],"diagnoses":[]}],"_id":"65401ebfd9e14800002ab199"}',
          patientId: "8f49150a-0fde-46f5-ab97-4583736e7ad7",
          hapiOperationOutcome: null,
          groupPopulations: [
            {
              groupId: "65401ea41b2c1c16e90c39fa",
              scoring: "Ratio",
              populationBasis: "true",
              populationValues: [
                {
                  id: "385976a9-a392-47a0-b3d8-6d80e8569c98",
                  criteriaReference: null,
                  name: "initialPopulation",
                  expected: true,
                  actual: false,
                },
                {
                  id: "317e0f81-22b8-447c-9980-4402ab25abbd",
                  criteriaReference: null,
                  name: "initialPopulation",
                  expected: true,
                  actual: false,
                },
                {
                  id: "3993aadf-b03f-434b-9f95-02de8b64b2bf",
                  criteriaReference: null,
                  name: "denominator",
                  expected: true,
                  actual: false,
                },
                {
                  id: "282d091f-a657-4526-afb1-e5a2811e7638",
                  criteriaReference: null,
                  name: "numerator",
                  expected: true,
                  actual: false,
                },
                {
                  id: "numeratorObservation0",
                  criteriaReference: "282d091f-a657-4526-afb1-e5a2811e7638",
                  name: "numeratorObservation",
                  expected: "30",
                  actual: null,
                },
              ],
              stratificationValues: [],
            },
          ],
          executionStatus: "NA",
        },
      ],
      groups: [
        {
          id: "65401ea41b2c1c16e90c39fa",
          scoring: "Ratio",
          populations: [
            {
              id: "385976a9-a392-47a0-b3d8-6d80e8569c98",
              name: "initialPopulation",
              definition: "Initial Population",
              associationType: "Denominator",
              description: "",
            },
            {
              id: "317e0f81-22b8-447c-9980-4402ab25abbd",
              name: "initialPopulation",
              definition: "Initial Population",
              associationType: "Numerator",
              description: "",
            },
            {
              id: "3993aadf-b03f-434b-9f95-02de8b64b2bf",
              name: "denominator",
              definition: "Denominator",
              associationType: null,
              description: "",
            },
            {
              id: "065916c0-aa58-4f47-80e5-9a28c86fb03c",
              name: "denominatorExclusion",
              definition: "",
              associationType: null,
              description: "",
            },
            {
              id: "282d091f-a657-4526-afb1-e5a2811e7638",
              name: "numerator",
              definition: "Numerator",
              associationType: null,
              description: "",
            },
            {
              id: "1eea3471-44ff-4f63-a52b-59c55ad21ac6",
              name: "numeratorExclusion",
              definition: "",
              associationType: null,
              description: "",
            },
          ],
          measureObservations: [
            {
              id: "12a6b4b0-c2e7-4a80-9d25-1159ed5cbfbc",
              definition: "Numer Observation",
              description: null,
              criteriaReference: "282d091f-a657-4526-afb1-e5a2811e7638",
              aggregateMethod: "Count",
            },
          ],
          groupDescription: "",
          improvementNotation: "",
          rateAggregation: "",
          measureGroupTypes: null,
          scoringUnit: "",
          stratifications: [],
          populationBasis: "true",
        },
      ],

      createdAt: "2023-10-26T14:56:14.802Z",
      createdBy: "Test1",
      measurementPeriodStart: "2023-01-02T00:00:00.000+00:00",
      measurementPeriodEnd: "2023-12-22T23:59:59.999+00:00",
      model: "QDM v5.6",
      scoring: "Ratio",
    } as unknown as Measure,
    patientResults: {
      Group1: {
        IPP: 1,
        DENOM: 1,
        DENEX: 0,
        NUMER: 1,
        NUMEX: 0,
        observation_values: [12],
        statement_relevance: {
          MAT6150Measure: {
            Patient: "NA",
            "Qualifying Encounters": "TRUE",
            "Initial Population": "TRUE",
            Denominator: "TRUE",
            Numerator: "TRUE",
            "Denonimator Exclusion": "NA",
            "Denom Observation": "NA",
            "Numer Observation": "TRUE",
          },
        },
        population_relevance: {
          IPP: true,
          DENOM: true,
          DENEX: true,
          NUMER: true,
          NUMEX: true,
          observation_values: true,
        },
        statement_results: {
          MAT6150Measure: {
            Patient: {
              library_name: "MAT6150Measure",
              statement_name: "Patient",
              relevance: "NA",
              final: "NA",
            },
            "Qualifying Encounters": {
              raw: [
                {
                  dataElementCodes: [
                    {
                      code: "4525004",
                      system: "2.16.840.1.113883.6.96",
                      version: null,
                      display: "Emergency department patient visit (procedure)",
                    },
                  ],
                  _id: "65401ebfd9e14800002ab197",
                  participant: [],
                  relatedTo: [],
                  qdmTitle: "Encounter, Performed",
                  hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                  qdmCategory: "encounter",
                  qdmStatus: "performed",
                  qdmVersion: "5.6",
                  _type: "QDM::EncounterPerformed",
                  description:
                    "Encounter, Performed: Emergency Department Visit",
                  codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                  id: "65401ed9d9e14800002ab1b2",
                  relevantPeriod: {
                    low: "2023-10-19T00:00:00.000+00:00",
                    high: "2023-10-24T00:00:00.000+00:00",
                    lowClosed: true,
                    highClosed: true,
                  },
                  facilityLocations: [],
                  diagnoses: [],
                },
                {
                  dataElementCodes: [
                    {
                      code: "448951000124107",
                      system: "2.16.840.1.113883.6.96",
                      version: null,
                      display: "Admission to observation unit (procedure)",
                    },
                  ],
                  _id: "65401ebfd9e14800002ab193",
                  participant: [],
                  relatedTo: [],
                  qdmTitle: "Encounter, Performed",
                  hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                  qdmCategory: "encounter",
                  qdmStatus: "performed",
                  qdmVersion: "5.6",
                  _type: "QDM::EncounterPerformed",
                  description: "Encounter, Performed: Observation Services",
                  codeListId: "2.16.840.1.113762.1.4.1111.143",
                  id: "65401ec2d9e14800002ab19c",
                  authorDatetime: "2023-10-26T00:00:00.000+00:00",
                  relevantPeriod: {
                    low: "2023-10-18T00:00:00.000+00:00",
                    high: "2023-10-25T00:00:00.000+00:00",
                    lowClosed: true,
                    highClosed: true,
                  },
                  facilityLocations: [],
                  diagnoses: [],
                },
              ],
              library_name: "MAT6150Measure",
              statement_name: "Qualifying Encounters",
              relevance: "TRUE",
              final: "TRUE",
            },
            "Initial Population": {
              raw: true,
              library_name: "MAT6150Measure",
              statement_name: "Initial Population",
              relevance: "TRUE",
              final: "TRUE",
            },
            Denominator: {
              raw: true,
              library_name: "MAT6150Measure",
              statement_name: "Denominator",
              relevance: "TRUE",
              final: "TRUE",
            },
            Numerator: {
              raw: true,
              library_name: "MAT6150Measure",
              statement_name: "Numerator",
              relevance: "TRUE",
              final: "TRUE",
            },
            "Denonimator Exclusion": {
              raw: true,
              library_name: "MAT6150Measure",
              statement_name: "Denonimator Exclusion",
              relevance: "NA",
              final: "NA",
            },
            "Denom Observation": {
              library_name: "MAT6150Measure",
              statement_name: "Denom Observation",
              relevance: "NA",
              final: "NA",
            },
            "Numer Observation": {
              library_name: "MAT6150Measure",
              statement_name: "Numer Observation",
              relevance: "TRUE",
              final: "FALSE",
            },
          },
        },
        clause_results: null,
        patient: "65401ebfd9e14800002ab199",
        measure: "6541113c15c2db0000aeb0ba",
        state: "complete",
      },
    },
  };
