import {
  AggregateFunctionType,
  BaseConfigurationTypes,
  Group,
  Measure,
  Model,
  PopulationType,
  TestCase,
} from "@madie/madie-models";
import { CqmExecutionPatientResultsByPopulationSet } from "../QdmCalculationService";
import { ExecutionStatusType } from "../CalculationService";

export interface QdmTestCaseProcessingScenario {
  testCase: TestCase;
  measureGroups: Group[];
  measure: Measure;
  patientResults: CqmExecutionPatientResultsByPopulationSet;
}

export const CV_PATIENT_WITH_OBS_RESULTS: QdmTestCaseProcessingScenario = {
  testCase: {
    id: "6525b28f4a75bf514e67c8d7",
    name: null,
    title: "TC1",
    series: "",
    description: "",
    createdAt: "2023-10-10T20:22:39.373Z",
    createdBy: "nate.moraca@semanticbits.com",
    lastModifiedAt: "2023-10-11T21:06:23.977Z",
    lastModifiedBy: "nate.moraca@semanticbits.com",
    validResource: true,
    json: "{}",
    patientId: "bdd160e5-21f6-45e4-bf60-911778878b4d",
    hapiOperationOutcome: null,
    executionStatus: ExecutionStatusType.NA,
    groupPopulations: [
      {
        groupId: "6525ae434a75bf514e67c8d5",
        scoring: "Continuous Variable",
        populationBasis: "true",
        populationValues: [
          {
            id: "d6c09032-abe1-43f5-812b-6319f50b0f44",
            criteriaReference: null,
            name: PopulationType.INITIAL_POPULATION,
            expected: true,
            actual: false,
          },
          {
            id: "bc57e09b-e2dd-4c46-9170-e8838e999dc6",
            criteriaReference: null,
            name: PopulationType.MEASURE_POPULATION,
            expected: true,
            actual: false,
          },
          {
            id: "1aa2593b-cb91-440a-816a-f5481bee2844",
            criteriaReference: null,
            name: PopulationType.MEASURE_POPULATION_EXCLUSION,
            expected: null,
            actual: null,
          },
          {
            id: "measurePopulationObservation0",
            criteriaReference: "bc57e09b-e2dd-4c46-9170-e8838e999dc6",
            name: PopulationType.MEASURE_POPULATION_OBSERVATION,
            expected: 22,
            actual: null,
          },
        ],
        stratificationValues: [],
      },
    ],
  },
  measureGroups: [
    {
      id: "6525ae434a75bf514e67c8d5",
      scoring: "Continuous Variable",
      populations: [
        {
          id: "d6c09032-abe1-43f5-812b-6319f50b0f44",
          name: PopulationType.INITIAL_POPULATION,
          definition: "Initial Population",
          associationType: null,
          description: "",
        },
        {
          id: "bc57e09b-e2dd-4c46-9170-e8838e999dc6",
          name: PopulationType.MEASURE_POPULATION,
          definition: "Measure Population",
          associationType: null,
          description: "",
        },
        {
          id: "1aa2593b-cb91-440a-816a-f5481bee2844",
          name: PopulationType.MEASURE_POPULATION_EXCLUSION,
          definition: "Measure Population Exception",
          associationType: null,
          description: "",
        },
      ],
      measureObservations: [
        {
          id: "65d84f4a-0edc-4c38-94ed-18f996f8f0c4",
          definition: PopulationType.MEASURE_POPULATION_OBSERVATION,
          description: null,
          criteriaReference: "bc57e09b-e2dd-4c46-9170-e8838e999dc6",
          aggregateMethod: AggregateFunctionType.MAXIMUM,
        },
      ],
      groupDescription: "",
      improvementNotation: "",
      rateAggregation: "",
      measureGroupTypes: null,
      scoringUnit: "",
      stratifications: [],
      populationBasis: "true",
    },
  ],
  measure: {
    id: "6525ae204a75bf514e67c8d3",
    cqlLibraryName: "QdmCvPatient2",
    measureName: "QdmCvPatient2",
    active: true,
    cqlErrors: false,
    errors: [],
    cql: "",
    elmJson: "",
    testCases: [],
    groups: [],
    measurementPeriodStart: new Date("2024-01-01T00:00:00.000+00:00"),
    measurementPeriodEnd: new Date("2024-12-31T23:59:59.999+00:00"),
    model: Model.QDM_5_6,
    scoring: "Continuous Variable",
    baseConfigurationTypes: [BaseConfigurationTypes.OUTCOME],
    patientBasis: true,
  } as unknown as Measure,
  patientResults: {
    "6525ae434a75bf514e67c8d5": {
      IPP: 1,
      MSRPOPL: 1,
      MSRPOPLEX: 0,
      observation_values: [22],
      statement_relevance: {
        QdmCvPatient2: {
          Patient: "NA",
          "SDE Ethnicity": "NA",
          "SDE Payer": "NA",
          "SDE Race": "NA",
          "SDE Sex": "NA",
          "Initial Population": "TRUE",
          "Measure Population": "TRUE",
          "Measure Population Exception": "TRUE",
          "Measure Observation": "TRUE",
          IP2: "NA",
        },
      },
      population_relevance: {
        IPP: true,
        MSRPOPL: true,
        MSRPOPLEX: true,
        observation_values: true,
      },
      statement_results: {
        QdmCvPatient2: {
          Patient: {
            library_name: "QdmCvPatient2",
            statement_name: "Patient",
            relevance: "NA",
            final: "NA",
          },
          "SDE Ethnicity": {
            raw: [],
            library_name: "QdmCvPatient2",
            statement_name: "SDE Ethnicity",
            relevance: "NA",
            final: "NA",
          },
          "SDE Payer": {
            raw: [],
            library_name: "QdmCvPatient2",
            statement_name: "SDE Payer",
            relevance: "NA",
            final: "NA",
          },
          "SDE Race": {
            raw: [],
            library_name: "QdmCvPatient2",
            statement_name: "SDE Race",
            relevance: "NA",
            final: "NA",
          },
          "SDE Sex": {
            raw: [],
            library_name: "QdmCvPatient2",
            statement_name: "SDE Sex",
            relevance: "NA",
            final: "NA",
          },
          "Initial Population": {
            raw: true,
            library_name: "QdmCvPatient2",
            statement_name: "Initial Population",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Population": {
            raw: true,
            library_name: "QdmCvPatient2",
            statement_name: "Measure Population",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Population Exception": {
            raw: false,
            library_name: "QdmCvPatient2",
            statement_name: "Measure Population Exception",
            relevance: "TRUE",
            final: "FALSE",
          },
          "Measure Observation": {
            library_name: "QdmCvPatient2",
            statement_name: "Measure Observation",
            relevance: "TRUE",
            final: "FALSE",
          },
          IP2: {
            raw: true,
            library_name: "QdmCvPatient2",
            statement_name: "IP2",
            relevance: "NA",
            final: "NA",
          },
        },
      },
      clause_results: null,
      patient: "6525b291a430df00002cbec0",
      measure: "652949aa9a1f060000763d86",
      state: "complete",
    },
  },
};

export const CV_EPISODE_WITH_OBS_RESULTS: QdmTestCaseProcessingScenario = {
  testCase: {
    id: "6520233da0940f4a5c9a779e",
    name: null,
    title: "TC1",
    series: "",
    description: "",
    createdAt: "2023-10-06T15:09:49.430Z",
    createdBy: "nate.moraca@semanticbits.com",
    lastModifiedAt: "2023-10-12T21:07:21.573Z",
    lastModifiedBy: "nate.moraca@semanticbits.com",
    validResource: true,
    json: "{}",
    patientId: "dc788bd3-f02b-4b3c-89a2-104c0b6e753e",
    hapiOperationOutcome: null,
    groupPopulations: [
      {
        groupId: "65202333a0940f4a5c9a779d",
        scoring: "Continuous Variable",
        populationBasis: "false",
        populationValues: [
          {
            id: "ad4bbc0d-e955-43de-bef7-29c4ce5c0f07",
            criteriaReference: null,
            name: PopulationType.INITIAL_POPULATION,
            expected: 3,
          },
          {
            id: "e0127aea-baff-4a9f-bff9-d1a980e8b255",
            criteriaReference: null,
            name: PopulationType.MEASURE_POPULATION,
            expected: 3,
          },
          {
            id: "measurePopulationObservation0",
            criteriaReference: "e0127aea-baff-4a9f-bff9-d1a980e8b255",
            name: PopulationType.MEASURE_OBSERVATION,
            expected: 6,
          },
          {
            id: "97942400-e1a1-4857-842b-b1cc0f5ebfd6",
            criteriaReference: null,
            name: PopulationType.MEASURE_POPULATION_EXCLUSION,
            expected: 2,
          },
        ],
        stratificationValues: [],
      },
    ],
    executionStatus: "fail",
  },
  measureGroups: [
    {
      id: "65202333a0940f4a5c9a779d",
      scoring: "Continuous Variable",
      populations: [
        {
          id: "ad4bbc0d-e955-43de-bef7-29c4ce5c0f07",
          name: PopulationType.INITIAL_POPULATION,
          definition: "Initial Population",
          associationType: null,
          description: "",
        },
        {
          id: "e0127aea-baff-4a9f-bff9-d1a980e8b255",
          name: PopulationType.MEASURE_POPULATION,
          definition: "Measure Population",
          associationType: null,
          description: "",
        },
        {
          id: "97942400-e1a1-4857-842b-b1cc0f5ebfd6",
          name: PopulationType.MEASURE_POPULATION_EXCLUSION,
          definition: "Measure Population Exclusion",
          associationType: null,
          description: "",
        },
      ],
      measureObservations: [
        {
          id: "a78c0d1f-7c81-48e3-abf3-4f2595ba5748",
          definition: "Measure Observation",
          description: null,
          criteriaReference: "e0127aea-baff-4a9f-bff9-d1a980e8b255",
          aggregateMethod: AggregateFunctionType.COUNT,
        },
      ],
      groupDescription: "",
      improvementNotation: "",
      rateAggregation: "",
      measureGroupTypes: null,
      scoringUnit: "",
      stratifications: [],
      populationBasis: "false",
    },
  ],
  measure: {
    id: "65202281a0940f4a5c9a779b",
    cqlLibraryName: "QdmCvEpisode2",
    measureName: "QdmCvEpisode2",
    active: true,
    cqlErrors: false,
    errors: [],
    cql: "",
    elmJson: "",
    testCases: [],
    groups: [],
    measurementPeriodStart: new Date("2024-01-01T00:00:00.000+00:00"),
    measurementPeriodEnd: new Date("2024-12-31T23:59:59.999+00:00"),
    model: Model.QDM_5_6,
    scoring: "Continuous Variable",
    baseConfigurationTypes: [BaseConfigurationTypes.OUTCOME],
    patientBasis: false,
  } as unknown as Measure,
  patientResults: {
    "65202333a0940f4a5c9a779d": {
      IPP: 3,
      observation_values: [6],
      MSRPOPL: 3,
      MSRPOPLEX: 2,
      episode_results: {
        "652023464ca40800001ad57d": {
          IPP: 1,
          MSRPOPL: 1,
          MSRPOPLEX: 1,
          observation_values: [],
        },
        "65285ed46bb5ec0000ab8a85": {
          IPP: 1,
          MSRPOPL: 1,
          MSRPOPLEX: 1,
          observation_values: [],
        },
        "65285fc96bb5ec0000ab8e10": {
          IPP: 1,
          MSRPOPL: 1,
          MSRPOPLEX: 0,
          observation_values: [6],
        },
      },
      statement_relevance: {
        QdmCvEpisode2: {
          Patient: "NA",
          "SDE Ethnicity": "NA",
          "SDE Payer": "NA",
          "SDE Race": "NA",
          "SDE Sex": "NA",
          "Initial Population": "TRUE",
          "Measure Population": "TRUE",
          "Measure Population Exclusion": "TRUE",
          "Measure Observation": "TRUE",
          IP2: "NA",
        },
      },
      population_relevance: {
        IPP: true,
        MSRPOPL: true,
        MSRPOPLEX: true,
        observation_values: true,
      },
      statement_results: {
        QdmCvEpisode2: {
          Patient: {
            library_name: "QdmCvEpisode2",
            statement_name: "Patient",
            relevance: "NA",
            final: "NA",
          },
          "SDE Ethnicity": {
            raw: [],
            library_name: "QdmCvEpisode2",
            statement_name: "SDE Ethnicity",
            relevance: "NA",
            final: "NA",
          },
          "SDE Payer": {
            raw: [],
            library_name: "QdmCvEpisode2",
            statement_name: "SDE Payer",
            relevance: "NA",
            final: "NA",
          },
          "SDE Race": {
            raw: [],
            library_name: "QdmCvEpisode2",
            statement_name: "SDE Race",
            relevance: "NA",
            final: "NA",
          },
          "SDE Sex": {
            raw: [],
            library_name: "QdmCvEpisode2",
            statement_name: "SDE Sex",
            relevance: "NA",
            final: "NA",
          },
          "Initial Population": {
            raw: [
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "652023404ca40800001ad578",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "652023464ca40800001ad57d",
                relevantPeriod: {
                  low: "2024-02-08T05:00:00.000+00:00",
                  high: "2024-02-10T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285eb96bb5ec0000ab8a46",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285ed46bb5ec0000ab8a85",
                relevantPeriod: {
                  low: "2024-02-27T05:00:00.000+00:00",
                  high: "2024-03-02T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285fc56bb5ec0000ab8deb",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285fc96bb5ec0000ab8e10",
                relevantPeriod: {
                  low: "2023-12-29T05:00:00.000+00:00",
                  high: "2024-01-04T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
            ],
            library_name: "QdmCvEpisode2",
            statement_name: "Initial Population",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Population": {
            raw: [
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "652023404ca40800001ad578",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "652023464ca40800001ad57d",
                relevantPeriod: {
                  low: "2024-02-08T05:00:00.000+00:00",
                  high: "2024-02-10T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285eb96bb5ec0000ab8a46",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285ed46bb5ec0000ab8a85",
                relevantPeriod: {
                  low: "2024-02-27T05:00:00.000+00:00",
                  high: "2024-03-02T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285fc56bb5ec0000ab8deb",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285fc96bb5ec0000ab8e10",
                relevantPeriod: {
                  low: "2023-12-29T05:00:00.000+00:00",
                  high: "2024-01-04T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
            ],
            library_name: "QdmCvEpisode2",
            statement_name: "Measure Population",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Population Exclusion": {
            raw: [
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "652023404ca40800001ad578",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "652023464ca40800001ad57d",
                relevantPeriod: {
                  low: "2024-02-08T05:00:00.000+00:00",
                  high: "2024-02-10T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285eb96bb5ec0000ab8a46",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285ed46bb5ec0000ab8a85",
                relevantPeriod: {
                  low: "2024-02-27T05:00:00.000+00:00",
                  high: "2024-03-02T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
            ],
            library_name: "QdmCvEpisode2",
            statement_name: "Measure Population Exclusion",
            relevance: "TRUE",
            final: "TRUE",
          },
          "Measure Observation": {
            library_name: "QdmCvEpisode2",
            statement_name: "Measure Observation",
            relevance: "TRUE",
            final: "FALSE",
          },
          IP2: {
            raw: [
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "652023404ca40800001ad578",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "652023464ca40800001ad57d",
                relevantPeriod: {
                  low: "2024-02-08T05:00:00.000+00:00",
                  high: "2024-02-10T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285eb96bb5ec0000ab8a46",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285ed46bb5ec0000ab8a85",
                relevantPeriod: {
                  low: "2024-02-27T05:00:00.000+00:00",
                  high: "2024-03-02T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
              {
                dataElementCodes: [
                  {
                    code: "4525004",
                    system: "2.16.840.1.113883.6.96",
                    version: null,
                    display: "Emergency department patient visit (procedure)",
                  },
                ],
                _id: "65285fc56bb5ec0000ab8deb",
                participant: [],
                relatedTo: [],
                qdmTitle: "Encounter, Performed",
                hqmfOid: "2.16.840.1.113883.10.20.28.4.5",
                qdmCategory: "encounter",
                qdmStatus: "performed",
                qdmVersion: "5.6",
                _type: "QDM::EncounterPerformed",
                description: "Encounter, Performed: Emergency Department Visit",
                codeListId: "2.16.840.1.113883.3.117.1.7.1.292",
                id: "65285fc96bb5ec0000ab8e10",
                relevantPeriod: {
                  low: "2023-12-29T05:00:00.000+00:00",
                  high: "2024-01-04T05:00:00.000+00:00",
                  lowClosed: true,
                  highClosed: true,
                },
                facilityLocations: [],
                diagnoses: [],
              },
            ],
            library_name: "QdmCvEpisode2",
            statement_name: "IP2",
            relevance: "NA",
            final: "NA",
          },
        },
      },
      clause_results: null,
      patient: "652023404ca40800001ad57a",
      measure: "652d3d01b82d450000f267f7",
      state: "complete",
    },
  },
};
